### PR TITLE
expose imageconfiguration in CRD

### LINKED ISSUE #13: Expose image to use in CRD
```
  ----    ------          ----   ----               -------
  Normal  Scheduled       2m35s  default-scheduler  Successfully assigned kube-system/nfs-provisioner-6d447d46b-j5lhw to alt-ksw-g-c01oco02
  Normal  AddedInterface  2m34s  multus             Add eth0 [10.200.9.239/23] from openshift-sdn
  Normal  Pulled          2m34s  kubelet            Container image "quay.io/kubernetes_incubator/nfs-provisioner:latest" already present on machine
```

relying on `latest` is a bit yolo :). It would be nice if one could configure the image to use in the CR. Then you can lock the tag and pull via internal proxies etc.

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes #13
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@Jooho PTAL?

**Comment by Jooho** [comment]
@davidkarlsen I am testing this PR with the latest version. It might need to fetch upstream. Give me some time to test it

**Comment by davidkarlsen** [comment]
> @davidkarlsen I am testing this PR with the latest version. It might need to fetch upstream. Give me some time to test it

You mean the upstream nfs server image?
The operator as such origined from this repo?

**Comment by Jooho** [comment]
Thanks for your commit. It is merged and will be released with NFS Provisioner 0.0.5 soon

**Pull request merged**
